# Exibe mensagens de erro valores inv?lidos (400)
server:
  error:
    include-message: always
    include-binding-errors: always

# habilita a impress?o dos comando SQL no log

spring:
  jpa:
    show-sql: true
    # Habilita data.sql
    defer-datasource-initialization: true
    # formata os SQL (quebra linha, identa etc)
    properties:
      hibernate:
        format_sql: true
  # indica qual a URL de acesso ao banco. A palavra "nome_banco" ao final ? o nome do banco de dados
  datasource:
    url: jdbc:h2:mem:jogos
  # Habilitando o H2 Console. Num navegador, permite o acesso a http://localhost:8080/h2-console
  h2:
    console:
      enabled: true



